title: Dev { 60 } IT  Solutions
description: Dev 60 IT Solutions.
url: https://www.dev60.com
#logo: /images/apple-touch-icon-ipad-retina-152x152.png

contact: '/contact/#wj-contact'
learn-more: '/about/#wj-features'
github: https://github.com/Dev60au
#youtube: https://www.youtube.com/webjeda

twitter:
  username: Dev60

social:
  name: Dev60
  links:
    - https://twitter.com/rana_15


#facebook:
 #app_id: 549480635219583
 #publisher: webjeda
 #admins: sharu725

include: ["_pages"]
exclude:
    - _extra


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

#review:
 # link: http://search.google.com/local/writereview?placeid=ChIJx113w8QUuzsR_3IiWBPrucE
  #short-link: https://goo.gl/fAcxe9

#review-link: 'https://www.google.com/search?q=Webjeda#lkt=LocalPoiReviews&lrd=0x3bbb14c4c3775dc7:0xc1b9eb13582272ff,3,5,,&trex=m_t:lcl_akp,rc_f:nav,rc_ludocids:13959446988327121663,rc_q:Webjeda,ru_q:Webjeda'


plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
